import { localeVocabulary, personalFieldTypes } from './locales.js';

// Supplemental formats, independently maintained from upstream Secretlint.
// Lengths are intentionally conservative: suspicious prefixes are redacted
// even when a pasted credential is truncated. No online verification occurs.
export const serviceRules = [
  ['gitlab-runner', /GR1348941[A-Za-z0-9_-]{16,}/g],
  ['firebase', /AAAA[A-Za-z0-9_-]{6,}:APA91b[A-Za-z0-9_-]{32,}/g],
  ['github', /(?:github_pat_|gh[pousr]_)[A-Za-z0-9_]{16,}/g],
  [
    'gitlab',
    /(?:glpat|gloas|gldt|glrt|glrtr|glcbt|glptt|glft|glimt|glagent|glwt|glsoat|glffct)-[A-Za-z0-9_-]{16,}/g,
  ],
  ['openai', /sk-(?:proj-|svcacct-|admin-)?[A-Za-z0-9_-]{16,}/g],
  ['anthropic', /sk-ant-(?:api\d{2}-)?[A-Za-z0-9_-]{16,}/g],
  ['aws', /(?:AKIA|ASIA|A3T[A-Z0-9])[A-Z0-9]{16}/g],
  [
    'google',
    /(?:AIza[A-Za-z0-9_-]{35}|GOCSPX-[A-Za-z0-9_-]{16,}|ya29\.[A-Za-z0-9_-]{20,})/g,
  ],
  ['slack', /(?:xox[a-z]|xapp|xwfp)-[A-Za-z0-9-]{16,}/g],
  [
    'stripe',
    /(?:[sr]k_(?:live|test)_[A-Za-z0-9]{16,}|whsec_[A-Za-z0-9]{16,})/g,
  ],
  ['sendgrid', /SG\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{20,}/g],
  ['twilio', /SK[a-fA-F0-9]{32}/g],
  ['npm', /npm_[A-Za-z0-9]{20,}/g],
  ['pypi', /pypi-[A-Za-z0-9_-]{30,}/g],
  ['telegram', /\d{8,12}:[A-Za-z0-9_-]{30,}/g],
  ['discord', /[MN][A-Za-z0-9_-]{23,}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{20,}/g],
  ['huggingface', /hf_[A-Za-z0-9]{20,}/g],
  ['shopify', /shp(?:at|ss|ca|pa)_[a-fA-F0-9]{32}/g],
  ['databricks', /dapi[a-fA-F0-9]{32}/g],
  ['square', /sq0(?:atp|csp)-[A-Za-z0-9_-]{20,}/g],
  ['mailchimp', /[a-fA-F0-9]{32}-us\d{1,2}/g],
  ['digitalocean', /do(?:pat|o|r)_v1_[a-fA-F0-9]{64}/g],
  ['vault', /(?:hvs|hvb|hvr)\.[A-Za-z0-9_-]{16,}/g],
  ['grafana', /(?:glc_|glsa_)[A-Za-z0-9_-]{20,}/g],
  ['linear', /lin_api_[A-Za-z0-9]{20,}/g],
  ['notion', /(?:secret_|ntn_)[A-Za-z0-9]{32,}/g],
  ['vercel', /vercel_[A-Za-z0-9_-]{20,}/g],
  ['jwt', /eyJ[A-Za-z0-9_-]{8,}\.eyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}/g],
];

// Label recognition is deliberately separate from general free-text NER.
export const labels = {
  credential: [
    'password',
    'passwd',
    'pwd',
    'passphrase',
    'credentials',
    'api key',
    'mot de passe',
    'kata sandi',
    'mật khẩu',
    'пароля',
    'паролем',
    'паролю',
    'contraseñas',
    'senhas',
    'şifresi',
    'पासवर्ड है',
    'secret',
    'token',
    'api_key',
    'apikey',
    'api-key',
    'authorization',
    'auth',
    'cookie',
    'accountkey',
    'client_secret',
    'private_key',
    'access_key',
    'access_token',
    'refresh_token',
    'session_key',
    'connectionstring',
    'sas',
    'sig',
    'senha',
    'contraseña',
    'clave',
    'mot_de_passe',
    'passwort',
    'пароль',
    'секрет',
    'токен',
    '密码',
    '密碼',
    '口令',
    'パスワード',
    '비밀번호',
    'كلمة المرور',
    'رمز الدخول',
    'סיסמה',
    'पासवर्ड',
    'şifre',
    'kata_sandi',
    'mật_khẩu',
    'รหัสผ่าน',
  ],
  PERSON: [
    'name',
    'full_name',
    'fullname',
    'first_name',
    'last_name',
    'givenname',
    'surname',
    'nom',
    'nombre',
    'nome',
    'имя',
    'фио',
    'фамилия',
    '姓名',
    '氏名',
    '이름',
    'الاسم',
    'שם',
    'नाम',
    'ad_soyad',
    'nama',
    'họ_tên',
    'ชื่อ',
  ],
  ADDRESS: [
    'address',
    'street_address',
    'adresse',
    'dirección',
    'endereço',
    'адрес',
    '地址',
    '住所',
    '주소',
    'العنوان',
    'כתובת',
    'पता',
    'adres',
    'alamat',
    'địa_chỉ',
  ],
  DATE_OF_BIRTH: [
    'date_of_birth',
    'dob',
    'birthdate',
    'fecha_de_nacimiento',
    'дата рождения',
    '出生日期',
    '生年月日',
    'تاريخ الميلاد',
  ],
  ID: [
    'passport',
    'passport_number',
    'ssn',
    'national_id',
    'tax_id',
    'inn',
    'инн',
    'social_security',
    'cpf',
    'aadhaar',
    'snils',
    'паспорт',
    'снилс',
    'инн',
    '身份证',
    '护照',
    '身分証',
    'جواز السفر',
  ],
};

for (const [, credential, ...fields] of localeVocabulary) {
  labels.credential.push(credential);
  fields.forEach((word, i) => {
    labels[personalFieldTypes[i]] ??= [];
    labels[personalFieldTypes[i]].push(word);
  });
}
for (const [type, words] of Object.entries(labels)) {
  labels[type] = [...new Set(words)].sort((a, b) => b.length - a.length);
}
